name: cba_course
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - pip=23.3.1
  - r-base=4.2
  - bioconductor-deseq2=1.38
  - bioconductor-degreport=1.34.0
  - bioconductor-summarizedexperiment=1.28.0
  - pip:
    - numpy==1.26
    - pandas==2.1.1
    - scipy==1.11.3
    - scikit-learn==1.3.2
    - matplotlib==3.8.0
    - seaborn==0.13.0
    - lifelines==0.27.4
    - gseapy==1.0.6
    - rpy2==3.5.14
    - biomart==0.9.2
    - pyvis==0.3.1
    - jupyter-book==0.15.1
    - jupyter-server<2.0.0