name: cba_course
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.10
  - pip=22.2
  - r-base=4.2
  - bioconductor-deseq2=1.38
  - bioconductor-degreport=1.34.0
  - bioconductor-summarizedexperiment=1.28.0
  - pip:
    - scipy==1.7.2
    - jupyter-book==0.13.1
    - pandas==1.5.1
    - matplotlib==3.5.3
    - lifelines==0.27.1
    - gseapy==1.0.3
    - rpy2==3.5.7
    - scikit-learn==1.2.1
    - seaborn==0.12.2
    - numpy
